spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/sqa?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
