spring:
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:15007/railway?createDatabaseIfNotExist=true
    username: root
    password: jDysimLBIXwGfESVEzsizqvfFdpCFxJf
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true